---
-  name: extending filesystem with existing size in client1
   hosts: client1
   remote_user: ansible
   become: true
   tasks:
     - name: extendig lv
       lvol:
          vg: sharevg
          lv: sharelv
          size: +100%FREE
     - name: resizing mount point
       filesystem:
                dev: /dev/sharevg/sharelv
                fstype: ext4
                resizefs: true
-  name: extending filesystem with new disk in client3
   hosts: client3
   remote_user: ansible
   become: true
   tasks:
     - name: partitioning a new disk
       parted:
         device: /dev/sdc
         number: 1
         state: present
     - name: creating apv extending vg
       lvg:
         vg: sharevg
         pvs: /dev/sdc1,/dev/sdb1
     - name: extending lv
       lvol:
         vg: sharevg
         lv: sharelv
         size: +100%FREE
     - name: resizing mount point
       filesystem:
              dev: /dev/sharevg/sharelv
              fstype: ext4
              resizefs: true         
