---
-  name: extending a file system
   hosts: dbclients
   remote_user: ansible
   become: true
   tasks:
    - name: extending a lv
      lvol:
        vg: sharevg
        lv: sharelv
        size: +100%FREE
    - name: extending file system
      filesystem:
              dev: /dev/sharevg/sharelv
              fstype: ext4
              resizefs: yes
                 
             
