---
-  name: httpd installation
   hosts: client3
   remote_user: ansible
   become: true
   tasks: 
    - name: installing httpd
      yum: name=httpd state=latest
    - name: copiying httpd.conf file to /var/tmp
      copy: src=/etc/httpd/conf/httpd.conf dest=/var/tmp
      notify:
         - restart httpd service
    - name: starting httpd service
      service: name=httpd state=started enabled=yes
   handlers: 
    - name: restart httpd service
      service: name=httpd state=restarted
