---
-  name: installing tomcat service
   hosts: dbclients
   remote_user: ansible
   become: true
   tasks: 
      - name: creating java home path
        file:
          path: /oracle/grid
          state: directory
        environment:
            JAVA_HOME: '/oracle/grid'
      - name: setting downloading path
        file:
          path: /usr/local/tomcat
          state: directory
      - name: downloading tomact file form website
        get_url:
             url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
             dest: /usr/local/tomcat
      - name: extracting tar file
        unarchive:
                src: /usr/local/tomcat/apache-tomcat-8.5.78.tar.gz
                dest: /usr/local/tomcat/
                remote_src: yes
      - name: moving apache-tomcat directory to /oracle/grid
        command: mv /usr/local/tomcat/apache-tomcat-8.5.78 /oracle/grid
      - name: running script
        script: /oracle/grid/apache-tomcat-8.5.78/bin/startup.sh

