---
     - name: partitioning a disk /dev/sdb
       parted: device=/dev/sdb number=1 state=present
     - name: creating a pv and vg
       lvg: vg=appvg pvs=/dev/sdb1 state=present
     - name: creating applv
       lvol: vg=appvg lv=applv size=500m state=present force=yes 
     - name: configuring filesystem
       filesystem: dev=/dev/appvg/applv fstype=ext4
     - name: mounting /appdata
       mount: src=/dev/appvg/applv fstype=ext4 path=/appdata state=mounted
     - name: partitioning a disk /dev/sdc
       parted: device=/dev/sdc number=1 state=present
     - name: creating a pv and vg
       lvg: vg=asadminvg pvs=/dev/sdc1 state=present
     - name: creating asadminlv
       lvol: vg=asadminvg lv=asadminlv size=1000m state=present force=yes
     - name: configuring filesystem
       filesystem: dev=/dev/asadminvg/asadminlv fstype=xfs
     - name: mounting /asadmindata
       mount: src=/dev/asadminvg/asadminlv fstype=xfs path=/asadmindata state=mounted
     - name: partitioning a disk /dev/sdd
       parted: device=/dev/sdd number=1 state=present
     - name: creating a pv and vg
       lvg: vg=wasvg pvs=/dev/sdd1 state=present
     - name: creating waslv
       lvol: vg=wasvg lv=waslv size=800m state=present force=yes
     - name: configuring filesystem
       filesystem: dev=/dev/wasvg/waslv fstype=ext4
     - name: mounting /wasdata
       mount: src=/dev/wasvg/waslv fstype=ext4 path=/wasdata state=mounted
     - name: partitioning a disk /dev/sde
       parted: device=/dev/sde number=1 state=present
     - name: creating a pv and vg
       lvg: vg=backupvg pvs=/dev/sde1 state=present
     - name: creating backuplv
       lvol: vg=backupvg lv=backuplv size=2500m state=present force=yes
     - name: configuring filesystem
       filesystem: dev=/dev/backupvg/backuplv fstype=xfs
     - name: mounting /backupdata
       mount: src=/dev/backupvg/backuplv fstype=xfs path=/backupdata state=mounted
     - name: partitioning a disk /dev/sdf
       parted: device=/dev/sdf number=1 state=present
     - name: creating a pv and vg
       lvg: vg=crmvg pvs=/dev/sdf1 state=present
     - name: creating crmlv
       lvol: vg=crmvg lv=crmlv size=1200m state=present force=yes
     - name: configuring filesystem
       filesystem: dev=/dev/crmvg/crmlv fstype=ext4
     - name: mounting /crmdata
       mount: src=/dev/crmvg/crmlv fstype=ext4 path=/crmdata state=mounted
     - name: changing privillages /appdata
       file: path=/appdata owner=appuser group=appgrp
     - name: changing privillages /asadmindata
       file: path=/asadmindata owner=asadmin group=asadmin
     - name: changing privillages /wasdata
       file: path=/wasdata owner=was group=was
     - name: changing privillages /backupdata
       file: path=/backupdata owner=avamar group=avamar
     - name: changing privillages /appdata
       file: path=/crmdata owner=crmuser group=crmgrp
